### ISSUE TITLE
hoverre logo szinváltás a fejlécben

### ISSUE THREAD

**Issue by tortadara** [nyiropet/fourcreation#10]

**Comment by nyiropet** [comment]
@tortadara Nézd csak majd meg a logót, mikor ráhoverelsz. Kicsit lassú az animáció.

**Comment by tortadara** [comment]
gusztustalanul menő!

**Comment by tortadara** [comment]
viszont az aloldalakon eltűnik az animáció, azonnal átvált a színesre ha hoverelsz

**Comment by nyiropet** [comment]
@tortadara Elvileg mostmár helyesen viselkedik.
