### ISSUE TITLE
mit csinálunk refkók

### ISSUE THREAD

**Issue by tortadara** [nyiropet/fourcreation#22]
a doksi végén van a szöveg, refkók mappában a képek, mockup "aloldal---mit-csinálunk" alja

**Comment by nyiropet** [comment]
@tortadara a proko.jpg felbontását kellene akkor követni.

**Comment by tortadara** [comment]
láttam hogy ezeket átméretezted közben, jók lesznek akkor?

**Comment by nyiropet** [comment]
igen írtam Pankusnak, gyorsiba összedobta nekem, hogy ne ilyen aprósággal szarakodjunk.

**Comment by tortadara** [comment]
@nyiropet megnéztem a tesztoldalon, és ez a méret se volt jó (nem fedte tökéletesen a fekete csík, plusz a minőség se volt elég jó), úgyhogy csináltam új képeket

**Comment by tortadara** [comment]
ugyanaz az hoverre szövegeltűnés / kivilágosodás kéne, mint a kik vagyunknál
