### ISSUE TITLE
körökben középre igazítva

### ISSUE THREAD

**Issue by tortadara** [nyiropet/fourcreation#8]

**Comment by nyiropet** [comment]
Please provide some information in more detail. @tortadara

**Comment by tortadara** [comment]
erről már annyiszor beszéltünk hogy nem tudom mi volt a vége, de ezeket közére lehet rakni (sorok számától függően) vagy ezt lehet kihozni belőle max?
![image](https://cloud.githubusercontent.com/assets/20743119/24862949/28561566-1dff-11e7-902d-f54e83df14f6.png)
