### ISSUE TITLE
nyitó képernyőn háttérben kép

### ISSUE THREAD

**Issue by tortadara** [nyiropet/fourcreation#9]

**Comment by tortadara** [comment]
ugyanúgy randomizálva, mint az alatta lévő blokkban, lehetőség szerint ne ugyanazt a kettőt sorsolja össze

**Comment by nyiropet** [comment]
Randomizálva van.

**Comment by tortadara** [comment]
zsírci

2017. ápr. 19. 15:20 ezt írta ("nyiropet" <notifications@github.com>):
